//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama_Uygulama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Müsteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Müsteriler()
        {
            this.Subelers = new HashSet<Subeler>();
        }
    
        public int MüsteriNo { get; set; }
        public string AdSoyad { get; set; }
        public string Telefon { get; set; }
        public Nullable<int> Yas { get; set; }
        public Nullable<int> MüsteriBakiye { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subeler> Subelers { get; set; }
    }
}
